version: '2'
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    user: "1000"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /srv/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
#    network_mode: 'host' # to test locally running service
#   grafana:
#     image: grafana/grafana:7.0.1
#     volumes:
#       - ./grafana/provisioning/:/etc/grafana/provisioning/
#     environment:
#       - GF_SECURITY_ADMIN_PASSWORD=admin
#       - GF_USERS_ALLOW_SIGN_UP=false
#       - GF_INSTALL_PLUGINS=grafana-piechart-panel
#     ports:
#       - 3000:3000
# #    network_mode: 'host' # to test locally running service
