version: "2"
services:
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
    depends_on:
      - keycloakdb

  keycloakdb:
    extends:
      file: keycloak.yml
      service: keycloakdb

  minio:
    extends:
      file: minio.yml
      service: minio

  quizservicedb:
    image: mongo:4.2.7
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8090:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=quizservicedb
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example

  # opencast-postgresql:
  #   extends:
  #     file: opencast.yml
  #     service: opencast-postgresql

  # opencast-activemq:
  #   extends:
  #     file: opencast.yml
  #     service: opencast-activemq

  # opencast-elasticsearch:
  #   extends:
  #     file: opencast.yml
  #     service: opencast-elasticsearch

  # opencast:
  #   extends:
  #     file: opencast.yml
  #     service: opencast
