version: '2'
services:
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
  minio:
    extends:
      file: minio.yml
      service: minio
