version: "2"
services:
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
  minio:
    extends:
      file: minio.yml
      service: minio

  opencast-postgresql:
    extends:
      file: opencast.yml
      service: opencast-postgresql

  opencast-activemq:
    extends:
      file: opencast.yml
      service: opencast-activemq

  opencast-elasticsearch:
    extends:
      file: opencast.yml
      service: opencast-elasticsearch

  opencast:
    extends:
      file: opencast.yml
      service: opencast
