version: "2"
services:
  gateway:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - "SPRING_PROFILES_ACTIVE=prod,swagger"
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - "EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/Gateway"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster"
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - "8080:8080"
  gateway-postgresql:
    image: "postgres:12.3"
    environment:
      - POSTGRES_USER=Gateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  courseservice:
    image: courseservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - "SPRING_PROFILES_ACTIVE=prod,swagger"
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - "EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://courseservice-postgresql:5432/CourseService"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster"
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
    depends_on:
      - courseservice-postgresql
  courseservice-postgresql:
    image: "postgres:12.3"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=CourseService
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  mediaservice:
    image: mediaservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - "SPRING_PROFILES_ACTIVE=prod,swagger"
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - "EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://mediaservice-postgresql:5432/MediaService"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster"
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
  mediaservice-postgresql:
    image: "postgres:12.3"
    environment:
      - POSTGRES_USER=MediaService
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  quizservice:
    image: quizservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - "SPRING_PROFILES_ACTIVE=prod,swagger"
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - "EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka"
      - "SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config"
      - "SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster"
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin

  quizservicedb:
    image: mongo:4.2.7
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8090:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=quizservicedb
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
    depends_on:
      - keycloakdb

  keycloakdb:
    extends:
      file: keycloak.yml
      service: keycloakdb

  minio:
    extends:
      file: minio.yml
      service: minio

  # opencast-postgresql:
  #   extends:
  #     file: opencast.yml
  #     service: opencast-postgresql

  # opencast-activemq:
  #   extends:
  #     file: opencast.yml
  #     service: opencast-activemq

  # opencast-elasticsearch:
  #   extends:
  #     file: opencast.yml
  #     service: opencast-elasticsearch

  # opencast:
  #   extends:
  #     file: opencast.yml
  #     service: opencast
