apiVersion: v1
kind: Secret
metadata:
  name: mediaservice-postgresql
  namespace: default
  labels:
    app: mediaservice-postgresql
type: Opaque
data:
  postgresql-password: NzczYmRjYjM5YWEwNGU2ZjRhOWQ0ZTY2OTU4NDAyZTE3NDhhMDkyNzcyMzUzMGE1NjM5OTUwOGZjODJi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaservice-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediaservice-postgresql
  template:
    metadata:
      labels:
        app: mediaservice-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.3
          env:
            - name: POSTGRES_USER
              value: MediaService
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediaservice-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: mediaservice-postgresql
  namespace: default
spec:
  selector:
    app: mediaservice-postgresql
  ports:
    - port: 5432
