#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDU1OTJlZThmZDA5ZWU0NGU4NjVkYjYwNzlkMDJmYmRhYmJlYzNjZmQyYzJmY2I5MDJlMDQ1ZjI1ZTliNGEyMmQ5MWQxNWZjN2ZhOWQ4OTRmOTYwNWQ5M2E0YjFhZTFkN2IwOA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
