commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - gateway-k8s/gateway-deployment.yml
  - gateway-k8s/gateway-service.yml
  - gateway-k8s/gateway-postgresql.yml
  - courseservice-k8s/courseservice-deployment.yml
  - courseservice-k8s/courseservice-service.yml
  - courseservice-k8s/courseservice-postgresql.yml
  - mediaservice-k8s/mediaservice-deployment.yml
  - mediaservice-k8s/mediaservice-service.yml
  - mediaservice-k8s/mediaservice-postgresql.yml
  # service discovery eureka/consul
  - registry-k8s/jhipster-registry.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
