version: '2'
services:
  keycloak:
    image: jboss/keycloak:10.0.0
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
#        '-Dkeycloak.frontendUrl=http://129.69.217.173:9080/auth',
#        '-Dkeycloak.forceBackendUrlToFrontendUrl=true',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
#     KEYCLOAK_USER: admin
#     KEYCLOAK_PASSWORD: admin
#     DB_VENDOR: postgres
#     DB_ADDR: keycloak-postgres
#     DB_USER: keycloak
#     DB_PASSWORD: "k3ycl04k"
##    - PROXY_ADDRESS_FORWARDING=true
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990
